# Generated by Django 2.0.1 on 2018-01-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180122_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='projects/expense/attachment/%Y/%m/%d/', verbose_name='Attachment'),
        ),
    ]
