language: python

python: "3.6"

sudo: required

install:
  - pip install poetry
  - poetry install
  - sh ./travis/before_script.sh

before_script:
  - export DJANGO_SETTINGS_MODULE="config.settings.test"
  - export SECRET_KEY="secret"
  - export DATABASE_URL=postgres://postgres:@localhost:5432/proma_test

script:
  - poetry run black --check .
  - poetry run flake8 .
  - poetry run pytest

services:
  - postgresql
