language: python

python: "3.6"

sudo: required

install:
  - pip install -r requirements/test.txt
  - sh ./travis/before_script.sh

before_script:
  - export DJANGO_SETTINGS_MODULE="config.settings.test"
  - export SECRET_KEY="secret"
  - export DB_NAME="proma_test"
  - export DB_USER="postgres"
  - export DB_PASSWORD=""

script:
  - make lint
  - make test

services:
  - postgresql
