# Generated by Django 2.0.1 on 2018-02-25 00:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import proma.invoices.models
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0004_auto_20180126_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(default=secrets.token_hex, editable=False, max_length=64, unique=True, verbose_name='Number')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue date')),
                ('due_date', models.DateField(default=proma.invoices.models.default_due_date, verbose_name='Due date')),
                ('opening_date', models.DateField(editable=False, null=True, verbose_name='Opening date')),
                ('payment_date', models.DateField(editable=False, null=True, verbose_name='Payment date')),
                ('cancellation_date', models.DateField(editable=False, null=True, verbose_name='Cancellation date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Tax %')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Tax total')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='invoices/invoice/attachment/%Y/%m/%d/', verbose_name='Attachment')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.Client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ('number',),
                'default_related_name': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('units', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Units')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.Invoice')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Item',
                'default_related_name': 'items',
            },
        ),
    ]
