# Generated by Django 2.0.1 on 2018-03-08 09:14

import secrets

from django.db import migrations


def gen_token(apps, schema_editor):
    Invoice = apps.get_model('invoices', 'Invoice')  # NOQA
    for row in Invoice.objects.all():
        row.token = secrets.token_hex()
        row.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_token'),
    ]

    operations = [
        migrations.RunPython(gen_token, reverse_code=migrations.RunPython.noop),
    ]
