# Generated by Django 2.0.1 on 2018-09-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20180308_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Payment notes'),
        ),
    ]
