# Generated by Django 2.0.1 on 2018-03-22 20:14

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company_logo', models.ImageField(blank=True, help_text='size should be 250pt x 100pt', null=True, upload_to='config/configuration/', verbose_name='Logo')),
                ('company_legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legal name')),
                ('company_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('company_tax_identifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tax identifier')),
                ('company_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('company_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('company_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('company_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('company_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
